set terminal png size 900,800 enhanced font "Helvetica,20"
set nokey
set output "tests/Generation/five_ellipses/wave.png"
set title "Clusters, Wave clustering (delta = 0.200000)"
set size ratio -1
plot 'tests/Algorithm/wave/data_wave.plt' index 0 w p title "0",\
'tests/Algorithm/wave/data_wave.plt' index 1 w p title "1",\
'tests/Algorithm/wave/data_wave.plt' index 2 w p title "2",\
'tests/Algorithm/wave/data_wave.plt' index 3 w p title "3",\
'tests/Algorithm/wave/data_wave.plt' index 4 w p title "4",\
'tests/Algorithm/wave/data_wave.plt' index 5 w p title "5",\
'tests/Algorithm/wave/data_wave.plt' index 6 w p title "6",\
'tests/Algorithm/wave/data_wave.plt' index 7 w p title "7",\
'tests/Algorithm/wave/data_wave.plt' index 8 w p title "8",\
'tests/Algorithm/wave/data_wave.plt' index 9 w p title "9",\
'tests/Algorithm/wave/data_wave.plt' index 10 w p title "10",\
'tests/Algorithm/wave/data_wave.plt' index 11 w p title "11",\
'tests/Algorithm/wave/data_wave.plt' index 12 w p title "12",\
'tests/Algorithm/wave/data_wave.plt' index 13 w p title "13",\
'tests/Algorithm/wave/data_wave.plt' index 14 w p title "14",\
'tests/Algorithm/wave/data_wave.plt' index 15 w p title "15",\
'tests/Algorithm/wave/data_wave.plt' index 16 w p title "16",\
'tests/Algorithm/wave/data_wave.plt' index 17 w p title "17",\
'tests/Algorithm/wave/data_wave.plt' index 18 w p title "18",\
'tests/Algorithm/wave/data_wave.plt' index 19 w p title "19",\
'tests/Algorithm/wave/data_wave.plt' index 20 w p title "20",\
'tests/Algorithm/wave/data_wave.plt' index 21 w p title "21",\
'tests/Algorithm/wave/data_wave.plt' index 22 w p title "22",\
'tests/Algorithm/wave/data_wave.plt' index 23 w p title "23",\
'tests/Algorithm/wave/data_wave.plt' index 24 w p title "24",\
'tests/Algorithm/wave/data_wave.plt' index 25 w p title "25",\
'tests/Algorithm/wave/data_wave.plt' index 26 w p title "26",\
'tests/Algorithm/wave/data_wave.plt' index 27 w p title "27",\
'tests/Algorithm/wave/data_wave.plt' index 28 w p title "28",\
'tests/Algorithm/wave/data_wave.plt' index 29 w p title "29",\
'tests/Algorithm/wave/data_wave.plt' index 30 w p title "30",\
'tests/Algorithm/wave/data_wave.plt' index 31 w p title "31",\
'tests/Algorithm/wave/data_wave.plt' index 32 w p title "32",\
'tests/Algorithm/wave/data_wave.plt' index 33 w p title "33",\
'tests/Algorithm/wave/data_wave.plt' index 34 w p title "34",\
'tests/Algorithm/wave/data_wave.plt' index 35 w p title "35",\
'tests/Algorithm/wave/data_wave.plt' index 36 w p title "36",\
'tests/Algorithm/wave/data_wave.plt' index 37 w p title "37",\
'tests/Algorithm/wave/data_wave.plt' index 38 w p title "38",\
'tests/Algorithm/wave/data_wave.plt' index 39 w p title "39",\
'tests/Algorithm/wave/data_wave.plt' index 40 w p title "40",\
'tests/Algorithm/wave/data_wave.plt' index 41 w p title "41",\
'tests/Algorithm/wave/data_wave.plt' index 42 w p title "42",\
'tests/Algorithm/wave/data_wave.plt' index 43 w p title "43",\
'tests/Algorithm/wave/data_wave.plt' index 44 w p title "44",\
'tests/Algorithm/wave/data_wave.plt' index 45 w p title "45",\
'tests/Algorithm/wave/data_wave.plt' index 46 w p title "46",\
'tests/Algorithm/wave/data_wave.plt' index 47 w p title "47",\
'tests/Algorithm/wave/data_wave.plt' index 48 w p title "48",\
'tests/Algorithm/wave/data_wave.plt' index 49 w p title "49",\
'tests/Algorithm/wave/data_wave.plt' index 50 w p title "50",\
'tests/Algorithm/wave/data_wave.plt' index 51 w p title "51",\
'tests/Algorithm/wave/data_wave.plt' index 52 w p title "52",\
'tests/Algorithm/wave/data_wave.plt' index 53 w p title "53",\
'tests/Algorithm/wave/data_wave.plt' index 54 w p title "54",\
'tests/Algorithm/wave/data_wave.plt' index 55 w p title "55",\
'tests/Algorithm/wave/data_wave.plt' index 56 w p title "56",\
'tests/Algorithm/wave/data_wave.plt' index 57 w p title "57",\
'tests/Algorithm/wave/data_wave.plt' index 58 w p title "58",\
'tests/Algorithm/wave/data_wave.plt' index 59 w p title "59",\
'tests/Algorithm/wave/data_wave.plt' index 60 w p title "60",\
'tests/Algorithm/wave/data_wave.plt' index 61 w p title "61",\
'tests/Algorithm/wave/data_wave.plt' index 62 w p title "62",\
'tests/Algorithm/wave/data_wave.plt' index 63 w p title "63",\
'tests/Algorithm/wave/data_wave.plt' index 64 w p title "64",\
'tests/Algorithm/wave/data_wave.plt' index 65 w p title "65"
