set terminal gif animate loop -1 optimize delay 15 background "#ffeedf" \
    font "Times-Roman,10" size 1280,960
set output "tests/Algorithm/forel/forel_algorithm.gif"
set size ratio -1
set nokey
set title "FOREL-algorithm"
do for [i=0:861] {
	plot 		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 0 w p title "#0",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 1 w p title "#1",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 2 w p title "#2",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 3 w p title "#3",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 4 w p title "#4",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 5 w p title "#5",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 6 w p title "#6",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 7 w p title "#7",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 8 w p title "#8",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 9 w p title "#9",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 10 w p title "#10",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 11 w p title "#11",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 12 w p title "#12",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 13 w p title "#13",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 14 w p title "#14",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 15 w p title "#15",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 16 w p title "#16",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 17 w p title "#17",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 18 w p title "#18",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 19 w p title "#19",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 20 w p title "#20",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 21 w p title "#21",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 22 w p title "#22",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 23 w p title "#23",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 24 w p title "#24",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 25 w p title "#25",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 26 w p title "#26",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 27 w p title "#27",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 28 w p title "#28",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 29 w p title "#29",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 30 w p title "#30",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 31 w p title "#31",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 32 w p title "#32",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 33 w p title "#33",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 34 w p title "#34",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 35 w p title "#35",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 36 w p title "#36",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 37 w p title "#37",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 38 w p title "#38",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 39 w p title "#39",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 40 w p title "#40",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 41 w p title "#41",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 42 w p title "#42",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 43 w p title "#43",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 44 w p title "#44",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 45 w p title "#45",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 46 w p title "#46",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 47 w p title "#47",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 48 w p title "#48",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 49 w p title "#49",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 50 w p title "#50",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 51 w p title "#51",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 52 w p title "#52",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 53 w p title "#53",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 54 w p title "#54",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 55 w p title "#55",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 56 w p title "#56",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 57 w p title "#57",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 58 w p title "#58",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 59 w p title "#59",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 60 w p title "#60",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 61 w p title "#61",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 62 w p title "#62",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 63 w p title "#63",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 64 w p title "#64",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 65 w p title "#65",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 66 w p title "#66",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 67 w p title "#67",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 68 w p title "#68",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 69 w p title "#69",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 70 w p title "#70",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 71 w p title "#71",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 72 w p title "#72",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 73 w p title "#73",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 74 w p title "#74",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 75 w p title "#75",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 76 w p title "#76",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 77 w p title "#77",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 78 w p title "#78",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 79 w p title "#79",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 80 w p title "#80",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 81 w p title "#81",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 82 w p title "#82",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 83 w p title "#83",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 84 w p title "#84",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 85 w p title "#85",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 86 w p title "#86",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 87 w p title "#87",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 88 w p title "#88",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 89 w p title "#89",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 90 w p title "#90",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 91 w p title "#91",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 92 w p title "#92",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 93 w p title "#93",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 94 w p title "#94",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 95 w p title "#95",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 96 w p title "#96",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 97 w p title "#97",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 98 w p title "#98",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 99 w p title "#99",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 100 w p title "#100",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 101 w p title "#101",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 102 w p title "#102",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 103 w p title "#103",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 104 w p title "#104",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 105 w p title "#105",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 106 w p title "#106",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 107 w p title "#107",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 108 w p title "#108",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 109 w p title "#109",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 110 w p title "#110",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 111 w p title "#111",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 112 w p title "#112",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 113 w p title "#113",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 114 w p title "#114",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 115 w p title "#115",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 116 w p title "#116",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 117 w p title "#117",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 118 w p title "#118",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 119 w p title "#119",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 120 w p title "#120",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 121 w p title "#121",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 122 w p title "#122",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 123 w p title "#123",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 124 w p title "#124",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 125 w p title "#125",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 126 w p title "#126",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 127 w p title "#127",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 128 w p title "#128",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 129 w p title "#129",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 130 w p title "#130",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 131 w p title "#131",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 132 w p title "#132",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 133 w p title "#133",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 134 w p title "#134",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 135 w p title "#135",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 136 w p title "#136",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 137 w p title "#137",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 138 w p title "#138",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 139 w p title "#139",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 140 w p title "#140",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 141 w p title "#141",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 142 w p title "#142",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 143 w p title "#143",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 144 w p title "#144",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 145 w p title "#145",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 146 w p title "#146",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 147 w p title "#147",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 148 w p title "#148",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 149 w p title "#149",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 150 w p title "#150",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 151 w p title "#151",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 152 w p title "#152",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 153 w p title "#153",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 154 w p title "#154",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 155 w p title "#155",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 156 w p title "#156",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 157 w p title "#157",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 158 w p title "#158",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 159 w p title "#159",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 160 w p title "#160",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 161 w p title "#161",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 162 w p title "#162",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 163 w p title "#163",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 164 w p title "#164",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 165 w p title "#165",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 166 w p title "#166",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 167 w p title "#167",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 168 w p title "#168",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 169 w p title "#169",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 170 w p title "#170",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 171 w p title "#171",\
		'tests/Algorithm/forel/forel/clusters_'.i.'.plt' index 172 w p title "#172",\
		'tests/Algorithm/forel/forel/circles_'.i.'.plt' using 1:2:3with circles lc rgb "red" title "circles"
}